name: genesis

services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:stable
    entrypoint:
      - anvil
      - --host=0.0.0.0
      - --auto-impersonate
      - --no-request-size-limit
      - --chain-id=48815
    ports:
      - 8545:8545

  gensrv:
    image: ghcr.io/goatnetwork/geth-gensrv:main
    build:
      context: gensrv
    ports:
      - 8080:8080
